#  nginx:
#  backend:
#  db:

#version: "3"
#services:
#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: .
#    ports:
#      - "3000:3000"
#  nginx:
#    build: ./nginx
#    ports:
#      - "80:80"
#      - "443:443"
#    depends_on:
#      - frontend
#      - backend

version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: .
    ports:
      - "3000:3000"
  nginx:
    container_name: nginx
    build:
      context: ./nginxfile
      dockerfile: .
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: .
    ports:
      - "7500:7500"
