#  nginx:
#  backend: 도커파일 RUN npm install이 나중에 깔려야하는이유
#  db:
version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: .
    ports:
      - "3000:3000"
    restart: always
