#  nginx:
#  backend: 도커파일 RUN npm install이 나중에 깔려야하는이유 / node 3000포트 켜지는 거 확인 / 내부 3001포트로 되어있는지 확인
#  db:
version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: .
    ports:
      - "3000:3001"
    restart: always
