#  db:
#    image: postgres:14.
#    container_name: postgres
#    restart : always
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: ""
version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: .
    ports:
      - "3000:3000"
  nginx:
    container_name: nginx
    build:
      context: ./nginxfile
      dockerfile: .
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend_api-gateway
  backend_api-gateway:
    container_name: backend_api-gateway
    build:
      context: ./backend/api-gateway
      dockerfile: .
    ports:
      - "7500:7500"
  backend_eureka-server:
    container_name: backend_eureka-server
    build:
      context: ./backend/eureka-server
      dockerfile: .
    ports:
      - "8761:8761"
  backend_user-service:
    container_name: backend_user-service
    build:
      context: ./backend/user-service
      dockerfile: .
    ports:
      - "9600:9600"
  backend_order-service:
    container_name: backend_order-service
    build:
      context: ./backend/order-service
      dockerfile: .
    ports:
      - "9601:9601"
  backend_seller-service:
    container_name: backend_seller-service
    build:
      context: ./backend/seller-service
      dockerfile: .
    ports:
      - "9602:9602"
