server:
  port: 7500

eurkeka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: fashion-apigateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:3000'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
      routes:
        - id: user-service #하나의 서비스의 이름
          uri: lb://USER-SERVICE # lb://eureka에 등록된 어플리케이션 이름으로 사용
          predicates:
            - Path=/user-service/join # 이 주소로 들어오는 값은 uri로 통신을 보낸다는 의미
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie # 쿠키값을 헤더에서 제거한다는 의미
            - RewritePath=/user-service/(?<segment>.*), /$\{segment} #/user-service이 부분을 url에서 생략한다는 의미
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter # 로그인, 회원가입 외에는 jwt토큰 인증이 필요하다.
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/itemList
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

token:
  secret: user-token #이 정보가 토큰 복호화할때 사용 (당연히 암호할때랑 같은 값이어야겠다.)
