create table member(
    pk_id integer primary key generated by default as identity,
    id varchar(40) unique,
    email varchar(60) unique,
    nickname varchar(20) not null,
    password varchar(30) not null,
    birth date,
    grade varchar(10) not null default 'welcome',
    join_date date
);

ALTER TABLE MEMBER ADD COLUMN password_encrypt varchar(300) NOT NULL;
ALTER TABLE MEMBER DROP COLUMN PASSWORD;
commit;