// 회원 테이블 /////////////////////////////////
create table member(
    pk_id integer primary key generated by default as identity,
    id varchar(40) unique,
    email varchar(60) unique,
    nickname varchar(20) not null,
    password_encrypt varchar(300) not null,
    birth date,
    grade varchar(10) not null default 'welcome',
    join_date timestamp not null default current_date
);

#ALTER TABLE MEMBER ADD COLUMN password_encrypt varchar(300) NOT NULL;
#ALTER TABLE MEMBER DROP COLUMN PASSWORD;
commit;

#alter table member alter column join_date set default current_timestamp;
#alter TABLE member ALTER COLUMN join_date TYPE timestamp;

// 주문 테이블 /////////////////////////////////
create table orders(
    order_id integer primary key generated by default as identity,
    pk_id integer not null,
    order_date timestamp not null default current_date ,
    CONSTRAINT fk_pk_id FOREIGN KEY(pk_id) REFERENCES "member"(pk_id) ON DELETE CASCADE ON UPDATE CASCADE
);

commit;
#alter table orders alter column status set default 'ORDER';
#alter table orders alter column order_date set default current_timestamp;
#alter table orders alter column order_date TYPE timestamp;

// 카테고리 테이블 /////////////////////////////////
//create table category(
//    category_id integer primary key generated by default as identity,
//    name varchar(30) not null,
//);

//commit;

// 판매자 테이블 /////////////////////////////////
create table seller(
    seller_id integer primary key generated by default as identity,
    id varchar(40) unique,
    company_name varchar(20) not null,
    password_encrypt varchar(300) not null,
    join_date timestamp not null default current_date
);

commit;
/#ALTER TABLE seller RENAME COLUMN NICKNAME TO COMPANY_NAME;
#alter TABLE seller ALTER COLUMN join_date TYPE timestamp;

// 상품 테이블 /////////////////////////////////
create table item(
    item_id integer primary key generated by default as identity,
    seller_id integer not null,
    item_name varchar(100) not null,
    price integer not null,
    quantity integer not null,
    category varchar(20) not null,
    CONSTRAINT fk_seller_id FOREIGN KEY(seller_id) REFERENCES "seller"(seller_id) ON DELETE CASCADE ON UPDATE CASCADE
);

#ALTER TABLE ITEM ADD COLUMN item_name varchar(100) NOT NULL;

commit;


// 주문 상품 테이블 ////////////////////////////
create table orderitem(
    orderitem_id integer primary key generated by default as identity,
    order_id integer not null,
    item_id integer not null,
    order_quantity integer not null,
    order_price  integer not null,
    order_status varchar(20) not null default 'ORDER',
    CONSTRAINT fk_order_id FOREIGN KEY(order_id) REFERENCES "orders"(order_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_item_id FOREIGN KEY(item_id) REFERENCES "item"(item_id) ON DELETE CASCADE ON UPDATE CASCADE
);

#ALTER TABLE ORDERITEM ADD COLUMN order_quantity integer NOT NULL;
#ALTER TABLE ORDERITEM ADD COLUMN order_price integer NOT NULL;
commit;